### ISSUE TITLE
ortho-profile rule generator

### ISSUE THREAD

**Issue by LinguList** [SAuderset/mixteca#1]
The link is [https://digling.org/calc/profiler](https://digling.org/calc/profiler). The profiles for rules is the second tool on the website.

The example should explain the major idea:

```
[1 a e i o u][2 m n] > [1 a e i o u][2 ◌̃ ◌̃]
```

yields the output:

```
am	ã
an	ã
em	ẽ
en	ẽ
im	ĩ
in	ĩ
om	õ
on	õ
um	ũ
un	ũ
```

So this can just be pasted to the orthoprofile.

**Comment by SAuderset** [comment]
cool, thanks! exactly what I needed

**Comment by LinguList** [comment]
And now example with "ku":

```
[1 ku] [2 a e i o u][3 ◌̃ ◌] > [1 kw] [2 a e i o u][3 ◌̃ ◌]
```

Yields

```
ku ã	kw ã
ku a	kw a
ku ẽ	kw ẽ
ku e	kw e
ku ĩ	kw ĩ
ku i	kw i
ku õ	kw õ
ku o	kw o
ku ũ	kw ũ
ku u	kw u
```
(was too lazy to type supercript "w" here)
