### ISSUE TITLE
languages.tsv needs corrections

### ISSUE THREAD

**Issue by LinguList** [SAuderset/mixteca#2]
Currently, the code does not work, because languages.tsv has several aspects that contradict our formats.

1. NA is not permitted, just leave the field blank instead if glottocodes are missing (this is always the case, also in concepts.tsv, of course not in orthography.tsv, as leaving a field empty will delete the value)
2. some glottocodes do not seem to work, but I think this will become clear if you update the languages.tsv, it will throw an error in the python console, and you can modify this (set to empty cell in the worst case)

**Comment by SAuderset** [comment]
Thanks for catching this. I corrected it and it now runs fine with respect to the languages.
