### ISSUE TITLE
'words with invalid segments' but those segments are in profile

### ISSUE THREAD

**Issue by SAuderset** [SAuderset/mixteca#3]
I have a lot of 'words with invalid segments' in Transcriptions.md that flag segments that are in the profile. 
E.g. `| SanMiguelChicahuaMixtec-116_year-1 | SanMiguelChicahuaMixtec | 116_year | k°iya | k <s> <<°>> </s> *i/i *y/ʒ *a/a |` but I have this in the orthography.tsv as  'k° | kʷ'. It doesn't show up in the segments list in Transcription.md, which I'm sure is the problem.
How can I fix this? @LinguList

**Comment by LinguList** [comment]
Now you need to work on your profile. To check this further, please do:

```
$ cldfbench lexibank.check_profile mixteca
```

This shows a couple of cases where your profile is insufficient (all in all only 14 types, of course more tokens, but no problem).

```
INFO    running check_profile on mixteca ...
<<ɡ>>	*a/a *³/⁴ <<ɡ>> *a/a ³ˀ/ˀ ³	a³ɡa³ˀ
³ˀ/ˀ 	*a/a *³/⁴ <<ɡ>> *a/a ³ˀ/ˀ ³	a³ɡa³ˀ
¹ˀ/ˀ 	*a/a *³/⁴ *i/i ¹ˀ/ˀ ¹	a³i¹ˀ
³ʰ/ʰ 	*a/a *³/⁴ k *o/o ³ʰ/ʰ ³	a³ko³ʰ
⁴ʰ/ʰ 	*a/a *³/⁴ ts *i/i ⁴ʰ/ʰ ⁴	a³tsi⁴ʰ
²ʰ/ʰ 	*d/ð *a/a *²/³ ʔ *a/a ²ʰ/ʰ ²	da²ʔa²ʰ
¹ʰ/ʰ 	*d/ð *e/e *⁴/⁴ ʔ l *o/o ¹ʰ/ʰ ¹	de⁴ʔlo¹ʰ
<<ⁿ>>	ð *u̧/ũ <<ⁿ>> <<ɡ>> *u/u	đu̧ⁿɡu
³²ʰ/ʰ	g *a/a *³/⁴ tʃ *i/i ³²ʰ/ʰ ³²	ɡa³tʃi³²ʰ
<<·>>	*i̧/ĩ <<·>> ɲ *u̧/ũ 	i̧·ñu̧
ʰ    	*j/h *a/a ʰ ¹³      	ja¹³ʰ
<<°>>	k <<°>> *a/a ʔ *a/a 	k°aʔa
<<̠>>	t *i/i *a/a *²/³ k + kʷ a <<̠>> *³/⁴ ʔ *a̠/a ¹ *³/⁴	tia²c-cua̠³'a̠³
*²³⁴/⁴³¹	*y/j *i/i *²/³ t *a/a *²³⁴/⁴³¹	yi²ta²³⁴
Found 14 errors in 211 segments.
```

**Comment by LinguList** [comment]
I mean, this output shows that you are missing `g` in your profile ;)

A glottalization diacritic stands alone, which is obviously also wrong. Same applies to aspiration diacritics (I think you swapped `source/target` in our `/` annotation. It is to be read as: `THIS IS WHAT I GIVE AS LINGUIST TO MY DATA/THIS IS WHAT I GIVE TO CLTS TO EVALUATE IT`.

**Comment by LinguList** [comment]
We also work with `^k` as initial `k` and `k` as normal k. If you have `^k` but not `^k°`, the greediness of the algorithm will see `°` as unknown element, so you need to add `^k°` to your profile.

**Comment by LinguList** [comment]
⁴³¹ is not a real tone, as tones show movements, and contours mean that the movement should go up and down. But this is a movement from 4 to 1, and it does not make sense to provide seemingly phonetic correctness by insisting it goes over 3, it could also go over 2, and scholars "hear" tones quite differently, as proven in numerous works in Sinitic languages. So I suggest to make sure your tone is phonologically distinctive, but stick to the rules we have, which means: falling and raising is two Chao numbers, contour is three, short tones one.

**Comment by SAuderset** [comment]
oh, I see, I missed the issue with all the environments (^ and $). Okay, I just replaced everything after the slash so it works with clts. Now it seems the profile works fine!
Could you share your script to extract one for each language (I think that is the next step)?

**Comment by LinguList** [comment]
```python
from csvw.dsv import UnicodeDictReader
from collections import defaultdict
from clldutils.text import strip_brackets
from unicodedata import normalize

with UnicodeDictReader('../cldf/forms.csv') as reader:
    data = [row for row in reader]

with UnicodeDictReader('../etc/orthography.tsv', delimiter="\t") as reader:
    profile = {}
    for row in reader:
        profile[normalize('NFC', row['Grapheme'])] = row['IPA']

languages = set([row['Language_ID'] for row in data])

profiles = {language: defaultdict(int) for language in languages}

errors = {}


lexemes = {}
for row in data:
    for char in row['Graphemes'].split():
        char = normalize('NFC', char)
        profiles[row['Language_ID']][char, profile.get(char, '?'+char)] += 1

    if [x for x in '˩˨˧˦˥' if x in row['Value']]:
        tone = False
        out = []
        for char in strip_brackets(row['Form']).split(' '):
            char = normalize('NFC', char)
            if [x for x in '˩˨˧˦˥' if x in char]:
                if tone:
                    out[-1] += char
                else:
                    out += [char]
                tone = True
            else:
                tone = False
                try:
                    out[-1] = char+out[-1]
                except IndexError:
                    out += [char]
        lexemes[row['Value']] = ''.join(out)

for language in languages:
    with open('../etc/orthography/'+language+'.tsv', 'w') as f:
        f.write('Grapheme\tIPA\tFrequency\n')
        for (char, ipa), freq in profiles[language].items():
            f.write('{0}\t{1}\t{2}\n'.format(char, ipa, freq))
            if ipa.startswith('?'):
                errors[char] = ipa[1:]

with open('../etc/lexemes2.tsv', 'w') as f:
    for a, b in lexemes.items():
        f.write(a+'\t'+b+'\tswap tones\n')

with open('addons.tsv', 'w') as f:
    for a, b in errors.items():
        f.write(a+'\t'+b+'\n')
```

This script I run it from having cd-ed into the folder `raw`. There is unnecessary stuff, but we can tweak it if you run into problems.

**Comment by SAuderset** [comment]
great, thank you, I will give it a try and report back!

**Comment by LinguList** [comment]
Ah, you have to create a folder `orthography` in `etc` first. Becareful, as it overwrites all profiles in `orthography`, so you should ideally use it once, and no more once you have created language-internal profiles ;)

**Comment by SAuderset** [comment]
ah okay, noted. thanks for the warning!

**Comment by SAuderset** [comment]
everything worked fine! will start correcting the individual profiles now
