### ISSUE TITLE
resolving conflicts within profiles

### ISSUE THREAD

**Issue by SAuderset** [SAuderset/mixteca#4]
How do I resolve overlaps within profiles? For Alacatlatzala Mixtec, for example, I have four sources, each of which uses a different orthography (even though two of them are by the same author). The issue I have is that the same grapheme needs to resolve to different IPA representations depending on the source. For example, \<u\> = [u ¹] in one source, but = [u ³] in the other source. The tone is really important for me, because I will investigate it systematically in a separate study. 

How can I address this correctly in the profile? @LinguList 
All the data have been collected in the same village and by the same person, so I can't really see these as distinct doculects.

**Comment by LinguList** [comment]
So you want to provide data for one variety but collect it from four sources? I recommend not to do that, but if you really want to do it, you need to represent the phonology very well. But in our framework, merging data from different sources is not supported, so I'd say you should in this case provide intermediate forms in your TSV file, that is: doing this manually.

What you can also do is: treat the data as four different varieties for now, but merge them later, when we upload data to EDICTOR.

**Comment by SAuderset** [comment]
I'm surprised that this issue hasn't come up before. If I'm collecting data (here a word list), why would I limit myself to just one source, if there are multiple available? 
The second option sounds preferable to me. Otherwise I'll be adjusting a lot by hand. If I want to go with that option, can I add an extension to the variety name, e.g. AlacatlatzalaMixtecA, AlacatlatzalaMixtecB, etc. - or is that a bad idea?

**Comment by LinguList** [comment]
Our rule is so far to not mix data from different sources, since when scholars did this in the past, they messed up the merged phonologies, since they were often not able to represent the sounds from different data truthfully. For this reason, I recommend all scholars to not merge data. We'll see to which degree this also applies to the data you merge, but the good thing is: if you have concept overlap, we can even use the approach to check if the conversion to CLTS yields similar results. E.g., if you have "hand" in one source and in another source, you can check if the CLTS representations are really identical when merging.

**Comment by SAuderset** [comment]
Yes, I definitely have overlapping entries sometimes. The reason I haven't filtered them out is a) because if they are completely identical, this will become apparent after conversion as you say, and b) because if they are not identical, this might help explain other discrepancies (especially later on with tone). 

If I go with the second version, is it okay to add extension to the doculects, e.g. AlacatlatzalaMixtecA, AlacatlatzalaMixtecB, etc.?

**Comment by LinguList** [comment]
I'd suggest to extend the ID in a regular manner then: Variety_A, Variety_B, etc., but you should never give `_A` etc. to non-variants, otherwise we cannot detect them.

And please do not filter any double-entries, obviously, they are important to see how well one can merge them.

**Comment by SAuderset** [comment]
Yes, I will do it that way, with _A, _B etc. Fortunately this issue should only arise with a few varieties. And yes, I've definitely kept all the the duplicates in.

**Comment by SAuderset** [comment]
Okay, I made it through all the profiles. I wanted to check them but when I run `cldfbench lexibank.check_profile mixteca` I get the following output, which clearly indicates I'm doing something wrong. I tried this also with moving the masterprofile out of the repo, but the result is the same.

<img width="930" alt="Screen Shot 2021-01-11 at 12 07 56" src="https://user-images.githubusercontent.com/40177170/104173241-c4e76200-5405-11eb-96ce-c69c1a1c3630.png">

@LinguList : could you tell me how to check the individual profiles?

**Comment by LinguList** [comment]
check profile so far does NOT work on individual profiles, so you better just run your cldfbench normal code, and then check the converted results.

**Comment by SAuderset** [comment]
ah yes, makes sense! worked perfectly, so I'll close this issues now. thanks a lot!
